[package]
name = "mobile"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "gpui_mobile_app"
crate-type = ["cdylib", "staticlib", "lib"]
path = "src/lib.rs"

[dependencies]
amategeko-core.workspace = true
amategeko-app.workspace = true
gpui.workspace = true
gpui-mobile.workspace = true
gpui-kit.workspace = true
log.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15"
android-activity = { version = "0.6", features = ["native-activity"] }
jni = "0.21"

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6"
